export enum GenericTextUtils {
  baseUrl = "https:tunes.com",
  getAllGenresUrl = "/genres/all",
  albumUrl = "/author",
  chapterUrl = "/chapter",
  step1 = "Genres",
  step2 = "Authors",
  step3 = "Chapters",
  step4 = "Personal Details",
  step1Error = "No genres selected, please select at least one genre.",
  step2Error = "No Authors selected, please select at least one author.",
  step3Error = "No Chapters selected, please select at least one chapter.",
  amount = "Amount",
  count = "Count",
  next = "Next",
  previous = "Previous",
  submit = "Submit",
}
