export enum GenericTextUtils {
  baseUrl = "https:tunes.com",
  getAllSingersUrl = "/genres/all",
  albumUrl = "/author",
  songUrl = "/song",
  step1 = "Genres",
  step2 = "Authors",
  step3 = "Songs",
  step4 = "Personal Details",
  step1Error = "No genres selected, please select at least one genre.",
  step2Error = "No Authors selected, please select at least one author.",
  step3Error = "No Songs selected, please select at least one song.",
  amount = "Amount",
  count = "Count",
  next = "Next",
  previous = "Previous",
  submit = "Submit",
}
